### ISSUE TITLE
Changing entrypoint

### ISSUE THREAD

**Issue by flolivaud** [ypereirareis/docker-php7cc#1]
Actually we can't use this docker image with gitlab-ci.
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1421

The right way to fix this is to change the entrypoint, see the docker best practices :
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/entrypoint

Thanks

**Comment by ypereirareis** [comment]
Hello !

Can you explain me the problem with my entry point ?
I'm following the best practices. The problem comes from gitlab-ci that does not allow to override the entry point so far.

So you need me to change my entrypoint to a script file ?? :smile: 

Bye !

**Comment by flolivaud** [comment]
[Example in Docker Documentation (Best Practices)](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/entrypoint):
> This script allows the user to interact with Postgres in several ways.
> 
> It can simply start Postgres:
> 
> `$ docker run postgres`
> Or, it can be used to run Postgres and pass parameters to the server:
> 
> `$ docker run postgres postgres --help`
>
> Lastly, it could also be used to start a totally different tool, such as Bash:
> `$ docker run --rm -it postgres bash`

Yes the problem actually come from gitlab-ci, but you don't follow the best practices linked above.

**Comment by ypereirareis** [comment]
Hi !
Tag 2.0 (docker image) should match your needs !
Tell me if not.
Bye.

**Comment by flolivaud** [comment]
Thank you.

It's working but we need to use the fullpath to php7cc (`/root/.composer/vendor/bin/php7cc`) because gitlab-ci run this script via bash.

It might be good to add `/root/.composer/vendor/bin/` to `$PATH`
